apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
spec:
  # list of containers
  containers:
    - name: hello-pod
      image: banuprakashyadav/debug:v1
      command: ["sleep", "100000"]
